### ISSUE TITLE
Replace deprecated acronym tag with abbr tag

### ISSUE THREAD

**Issue by kogakure** [PedroLamas/gatsby-remark-acronyms#1]
Nice plugin and really useful! 🙏 

I would recommend to replace the `<acronym>` tag with the `<abbr>` tag, as the tag is [obsolete and no longer recommended](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/acronym), because it was removed in HTML5. The rest of the API is exactly the same.

**Comment by PedroLamas** [comment]
Wow, thanks for pointing that out, I sure was not aware of it!! I'll get the fix in a minute!

**Comment by PedroLamas** [comment]
I just released 1.0.8 with this change in it! Thanks!! 😄

**Comment by kogakure** [comment]
Thank you a lot 🎉 (I think the docs need now some update, too 😉).

**Comment by PedroLamas** [comment]
FYI, I've unpublished 1.0.8, updated the README.md file and published as 1.1.0 (bumped minor version) as this update might require some minor breaking changes on consumers.
