### ISSUE TITLE
How to add an external file with acronyms?

### ISSUE THREAD

**Issue by asifkabani** [PedroLamas/gatsby-remark-acronyms#229]
Hello, thank you for this plugin and it is a great help. However, my blog will keep adding acronyms and I am trying to figure out a better way to organize this. The `gatsby-config` file will not allow `import` statements so this is a bit tough to figure out. I have a `dictionary.js` file with an object of acronyms and I want to pass that object to the `options` instead of inline coding them in the `gatsby-config` file. Anyway around this?

**Comment by PedroLamas** [comment]
You can use the`require` keyword to import external files, as you can see here: https://github.com/PedroLamas/pedrolamas.com/blob/master/gatsby-config.js#L4

**Comment by asifkabani** [comment]
@PedroLamas thank you this worked!
