### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by donaldboulton** [pedrolamas/gatsby-remark-acronyms#248]
### Is your feature request related to a problem? Please describe

Please update to React 18.2.0 and Gatsby version 5. I still works on both getting build warnings.

### Describe the solution you'd like

OK

### Describe alternatives you've considered

Ok

### Additional information

Ok

**Comment by pedrolamas** [comment]
I just released [v1.2.1](https://www.npmjs.com/package/gatsby-remark-acronyms) that should mitigate those warnings!

**Comment by donaldboulton** [comment]
No Build warnings and works great with v1.2.1
Your wonderful thank you and God Bless You.
Thanks
Donald Boulton
